### ISSUE TITLE
需要新歌手！

### ISSUE THREAD

**Issue by awoyai** [lvyueyang/bb-music-order-open#1]
歌单可以新增下，许嵩、汪苏泷、孙燕姿、告五人的吗，或者可以告诉我歌单是怎么生成的吗

**Comment by lvyueyang** [comment]
我明天出一个使用文档

**Comment by awoyai** [comment]
感谢 ！！！！！

**Comment by lvyueyang** [comment]
可以更新到最新版本了，这是教程
https://juejin.cn/post/7431454931264274469
